INSERT INTO tear_entries (mood, note, reasons, date) VALUES
  ('sad',   'watched the news alone',            ARRAY['unknown'],  '2026-01-05'),
  ('happy', 'cat sat on my lap for an hour',     ARRAY['joy'],      '2026-01-09'),
  ('sad',   'rain and no umbrella',              ARRAY['unknown'],  '2026-01-07'),
  ('sad',   'thought about the old job again',   ARRAY['work'],     '2026-01-14'),
  ('yawn',  'so tired i cried in the shower',    ARRAY['body'],     '2026-01-14'),
  ('yawn',  'deadline pushed again',             ARRAY['work'],     '2026-01-12'),
  ('happy', 'stranger held the door',            ARRAY['joy'],      '2026-01-17'),
  ('happy', 'a song made me feel understood',    ARRAY['music'],    '2026-01-20'),
  ('sad',   'a memory came out of nowhere',      ARRAY['memory'],   '2026-01-22'),
  ('sad',   'forgot what her laugh sounded like',ARRAY['memory'],   '2026-01-25'),
  ('yawn',  'coffee went cold twice',            ARRAY['body'],     '2026-01-28'),
  ('happy', 'called mom, she laughed a lot',     ARRAY['friends'],  '2026-02-01'),
  ('sad',   'applied to 6 jobs today',           ARRAY['work'],     '2026-02-01'),
  ('happy', 'first warm day this year',          ARRAY['joy'],      '2026-02-03'),
  ('yawn',  'fell asleep mid-movie, woke crying',ARRAY['unknown'],  '2026-02-05'),
  ('happy', 'the 5pm light hit just right',      ARRAY['joy'],      '2026-02-07'),
  ('sad',   'scrolled too far back in photos',   ARRAY['memory'],   '2026-02-08'),
  ('sad',   'a 2019 song on shuffle',            ARRAY['music'],    '2026-02-10'),
  ('happy', 'someone texted to check in',        ARRAY['friends'],  '2026-02-10'),
  ('yawn',  'eyes burned before noon',           ARRAY['body'],     '2026-02-11'),
  ('sad',   'couldn''t explain why, just did',   ARRAY['unknown'],  '2026-02-13'),
  ('sad',   'rejection email at 7am',            ARRAY['work'],     '2026-02-14'),
  ('happy', 'finished the book at 2am',          ARRAY['music'],    '2026-02-16'),
  ('yawn',  'three hour nap, woke up heavy',     ARRAY['body'],     '2026-02-18'),
  ('sad',   'said goodbye at the airport',       ARRAY['friends'],  '2026-02-19'),
  ('happy', 'made dumplings from memory',        ARRAY['joy'],      '2026-02-20'),
  ('yawn',  'body just gave out',                ARRAY['body'],     '2026-02-21');
