import { Mood, Intensity } from './types';

export const SEED_ENTRIES: Array<{ mood: Mood; note: string; intensity: Intensity; nickname: string; date: string }> = [
  { mood: 'sad',     note: 'watched the news alone',            intensity: 'flow',  nickname: 'syc', date: '2026-01-05' },
  { mood: 'touched', note: 'cat sat on my lap for an hour',     intensity: 'mist',  nickname: 'syc', date: '2026-01-09' },
  { mood: 'sad',     note: 'thought about the old job again',   intensity: 'flow',  nickname: 'syc', date: '2026-01-14' },
  { mood: 'unsure',  note: 'so tired i cried in the shower',    intensity: 'flow',  nickname: 'syc', date: '2026-01-14' },
  { mood: 'touched', note: 'a song made me feel understood',    intensity: 'mist',  nickname: 'syc', date: '2026-01-20' },
  { mood: 'sad',     note: 'a memory came out of nowhere',      intensity: 'flow',  nickname: 'syc', date: '2026-01-22' },
  { mood: 'touched', note: 'called mom, she laughed a lot',     intensity: 'mist',  nickname: 'syc', date: '2026-02-01' },
  { mood: 'sad',     note: 'applied to 6 jobs today',           intensity: 'pour',  nickname: 'syc', date: '2026-02-01' },
  { mood: 'unsure',  note: 'fell asleep mid-movie, woke crying', intensity: 'mist', nickname: 'syc', date: '2026-02-05' },
  { mood: 'touched', note: 'the 5pm light hit just right',      intensity: 'mist',  nickname: 'syc', date: '2026-02-07' },
  { mood: 'sad',     note: 'a 2019 song on shuffle',            intensity: 'flow',  nickname: 'syc', date: '2026-02-10' },
  { mood: 'touched', note: 'someone texted to check in',        intensity: 'mist',  nickname: 'syc', date: '2026-02-10' },
  { mood: 'sad',     note: 'rejection email at 7am',            intensity: 'pour',  nickname: 'syc', date: '2026-02-14' },
  { mood: 'unsure',  note: 'three hour nap, woke up heavy',     intensity: 'flow',  nickname: 'syc', date: '2026-02-18' },
  { mood: 'touched', note: 'made dumplings from memory',        intensity: 'mist',  nickname: 'syc', date: '2026-02-20' },
  { mood: 'sad',     note: 'rain and no umbrella',              intensity: 'flow',  nickname: 'syc', date: '2026-01-07' },
  { mood: 'unsure',  note: 'deadline pushed again',             intensity: 'mist',  nickname: 'syc', date: '2026-01-12' },
  { mood: 'touched', note: 'stranger held the door',            intensity: 'mist',  nickname: 'syc', date: '2026-01-17' },
  { mood: 'sad',     note: 'forgot what her laugh sounded like', intensity: 'pour', nickname: 'syc', date: '2026-01-25' },
  { mood: 'unsure',  note: 'coffee went cold twice',            intensity: 'mist',  nickname: 'syc', date: '2026-01-28' },
  { mood: 'touched', note: 'first warm day this year',          intensity: 'mist',  nickname: 'syc', date: '2026-02-03' },
  { mood: 'sad',     note: 'scrolled too far back in photos',   intensity: 'pour',  nickname: 'syc', date: '2026-02-08' },
  { mood: 'unsure',  note: 'eyes burned before noon',           intensity: 'mist',  nickname: 'syc', date: '2026-02-11' },
  { mood: 'sad',     note: "couldn't explain why, just did",    intensity: 'flow',  nickname: 'syc', date: '2026-02-13' },
  { mood: 'touched', note: 'finished the book at 2am',          intensity: 'flow',  nickname: 'syc', date: '2026-02-16' },
  { mood: 'sad',     note: 'said goodbye at the airport',       intensity: 'pour',  nickname: 'syc', date: '2026-02-19' },
  { mood: 'unsure',  note: 'body just gave out',                intensity: 'flow',  nickname: 'syc', date: '2026-02-21' },
];
